### ISSUE TITLE
Make Harmony IDs unique

### ISSUE THREAD

**Issue by pardeike** [jecrell/JecsTools#3]
Harmony IDs identify the mod that is patching the methods. They should be unique. Since this is a library that is potentially used by several mods, it is not ok to have the same ID hard coded within the library. 

Suggestion: add support for a prefix that is combined with the internal IDs to make them unique.

**Comment by erdelf** [comment]
Not an issue. This library isn't supposed to be included in the mod, just referenced. It's more of a framework than a library.
